# Generated by Django 2.2.8 on 2019-12-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lithiumadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='salesforce_case',
            field=models.CharField(default='_', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='title',
            field=models.CharField(default='_', max_length=100),
            preserve_default=False,
        ),
    ]
