# Generated by Django 2.2.8 on 2019-12-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lithiumadmin', '0002_auto_20191206_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='severity',
            field=models.CharField(choices=[('SEV1', 'Severity 1'), ('SEV2', 'Severity 2'), ('SEV3', 'Severity 3'), ('SEVN', 'None')], default='SEV3', max_length=4),
        ),
    ]
