# Generated by Django 2.2.8 on 2019-12-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lithiumadmin', '0003_auto_20191206_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='developer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='files_location',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, path='/root'),
            preserve_default=False,
        ),
    ]
