# Generated by Django 2.2.8 on 2019-12-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lithiumadmin', '0003_auto_20191206_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownBug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_case', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('affected_versions', models.CharField(max_length=100)),
                ('fix_versions', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='associated_bug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bug_cases', to='lithiumadmin.Customer'),
        ),
        migrations.AlterField(
            model_name='case',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_cases', to='lithiumadmin.Customer'),
        ),
    ]
