# Generated by Django 2.2.8 on 2019-12-18 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lithiumadmin', '0004_auto_20191218_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='associated_bug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bug_cases', to='lithiumadmin.KnownBug'),
        ),
    ]
