# Generated by Django 2.2.8 on 2019-12-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lithiumadmin', '0004_auto_20191206_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='files_location',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
