# Generated by Django 2.2.8 on 2019-12-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lithiumadmin', '0007_customer_salesforce_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='salesforce_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
