# Generated by Django 2.2.8 on 2019-12-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lithiumadmin', '0008_auto_20191218_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='salesforce_name',
            field=models.CharField(default='NON', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
